shdjkhsad

diff --git a/sources/nvidia-driver-kainatos_25.1.02_all/DEBIAN/postinst b/sources/nvidia-driver-kainatos_25.1.02_all/DEBIAN/postinst
--- a/sources/nvidia-driver-kainatos_25.1.02_all/DEBIAN/postinst
+++ b/sources/nvidia-driver-kainatos_25.1.02_all/DEBIAN/postinst
@@ -1,14 +1,14 @@
-#!/bin/sh
-set -e
-
-case "$1" in
-    configure)
-        echo "Updating initramfs for all installed kernels..."
-        update-initramfs -u -k all || {
-            echo "Error: Failed to update initramfs" >&2
-            exit 1
-        }
-        ;;
-esac
-
-exit 0
+# #!/bin/sh
+# set -e
+#
+# case "$1" in
+#     configure)
+#         echo "Updating initramfs for all installed kernels..."
+#         update-initramfs -u -k all || {
+#             echo "Error: Failed to update initramfs" >&2
+#             exit 1
+#         }
+#         ;;
+# esac
+#
+# exit 0
